apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server-external
spec:
  type: LoadBalancer
  selector:
    io.kompose.service: server
  ports:
  - name: http
    port: 80
    targetPort: 8080
