name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
    
      env:
        GCP_KEY_SECRET: ${{ secrets.GCP_KEY_SECRET }}
      run: |
        echo "$GCP_KEY_SECRET" | base64 -d > /key.json
        export GOOGLE_APPLICATION_CREDENTIALS=/key.json
        curl -X POST  https://us-central1-cr-lab-hraizada-2906225331.cloudfunctions.net/function-1  --header "Authorization:bearer ${{ GOOGLE_APPLICATION_CREDENTIALS }}"   "Content-Type:application/json"  --data '{}' 
       
     