name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/783027060290/locations/global/workloadIdentityPools/test-cloudfunction/providers/demo-cloud'
        service_account: 'terraform-account@cr-lab-hraizada-2906225331.iam.gserviceaccount.com'
    - name: Set up secret file
    
      env:
        GCP_KEY_SECRET: ${{ secrets.GCP_KEY_SECRET }}
      run: |
        echo ${{ steps.auth.outputs.access_token }}
        curl -X POST  https://us-central1-cr-lab-hraizada-2906225331.cloudfunctions.net/function-1 --header "Authorization: bearer ${{ steps.auth.outputs.access_token }}"  --data '{}' 
    - name: Set up secret file2
      env:
        TOKEN_PASSWORD: ${{ steps.auth.outputs.access_token }}
        
      run: |
        echo $TOKEN_PASSWORD >> secrets.txt
       
    - name: Run tmate
      uses: mxschmitt/action-tmate@v2

     