name: Show Me the S3cr3tz
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: false
        default: 'Mona the Octocat'
      PATCH:
        description: 'location'
        required: false
        default: 'The Octoverse'

jobs:
  checkPermisions:
    name: checkPermisions
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
        # token_format: 'id_token'
        # workload_identity_provider: projects/783027060290/locations/global/workloadIdentityPools/test-cloudfunction/providers/demo-cloud
        # service_account: 'terraform-account@cr-lab-hraizada-2906225331.iam.gserviceaccount.com'
        # id_token_audience:  'https://iam.googleapis.com/projects/783027060290/locations/global/workloadIdentityPools/test-cloudfunction/providers/demo-cloud'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    
    - name: Set up secret file
    
      env:
        GCP_KEY_SECRET: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: |
       curl -X POST  https://us-central1-cr-lab-hraizada-2906225331.cloudfunctions.net/function-1 --header "Authorization: bearer $(gcloud auth print-identity-token)"  -d '{}' 
  provisionVM:
    name: provisionVM
    runs-on: ubuntu-latest
    needs: checkPermisions
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
       
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    
    - name: Set up secret file
    
      env:
        GCP_KEY_SECRET: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: |
       PATCH=$(curl -X POST  https://us-central1-cr-lab-hraizada-2906225331.cloudfunctions.net/function-2 --header "Authorization: bearer $(gcloud auth print-identity-token)"  -d '{}') 
       echo $PATCH
    - name: check status
      if: ${{ PATCH }} != "Success"
      run: |
       exit 1
    # - name: Set up secret file2
    #   env:
    #     TOKEN_PASSWORD: ${{ secrets.GOOGLE_CREDENTIALS }}
        
    #   run: |
    #     echo $TOKEN_PASSWORD >> secrets.json
       
    # - name: Run tmate
    #   uses: mxschmitt/action-tmate@v2

     